### ISSUE TITLE
Azure ML (SNGM & MNMG)

### ISSUE THREAD

**Issue by mmccarty** [rapidsai/deployment#15]

**Comment by skirui-source** [comment]
@jacobtomlinson,

In setting up AzureML workspace following these [instructions](https://docs.rapids.ai/deployment/stable/cloud/azure/azureml.html)-
- Step 5: clone [notebooks-contrib/azureml repo](https://github.com/rapidsai-community/notebooks-contrib/tree/main/the_archive/archived_rapids_blog_notebooks/azureml), the[ `start_azureml.py`](https://github.com/rapidsai-community/notebooks-contrib/blob/main/the_archive/archived_rapids_blog_notebooks/azureml/start_azureml.py) script installs older version of rapids and dependencies in this [yaml file](https://github.com/rapidsai-community/notebooks-contrib/blob/main/the_archive/archived_rapids_blog_notebooks/azureml/rapids/rapids-0.10.yml) (needs to be upgraded to the latest v23.04) --- 
- Do i need to manually generate requirements file,  Can we automate this like we did with the multi-stage build  PR? 


Whereas these  [instructions](https://github.com/rapidsai/cloud-ml-examples/blob/main/azure/README.md) show how to run workflows in AzureML using Rapids docker container (step 2a) or conda env (3a). 

**
Q: Which method do we want to follow? Especially given that the  [notebooks-contrib/azureml repo](https://github.com/rapidsai-community/notebooks-contrib/tree/main/the_archive/archived_rapids_blog_notebooks/azureml) is outdated and archived?
