### ISSUE TITLE
Version templating not working in includes

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#155]
After #143 the templating isn't working for fragments in `_includes`. I guess they don't go through the `source-read` pipeline.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/1610850/220708174-ceb5245c-1700-48a2-9997-7070f620505c.png">

**Comment by betatim** [comment]
Another place where the templating didn't work https://docs.rapids.ai/deployment/nightly/platforms/kubernetes.html

<img width="747" alt="Screenshot 2023-02-22 at 18 38 57" src="https://user-images.githubusercontent.com/1448859/220710665-dc622c9e-0657-4ee7-a347-05ae454a67c7.png">

**Comment by betatim** [comment]
Another page where the templating didn't work: https://docs.rapids.ai/deployment/nightly/cloud/gcp/compute-engine.html

**Comment by mroeschke** [comment]
`azure-vm.md` is impacted by the OP
