### ISSUE TITLE
Copy button copies too much of the code block's content

### ISSUE THREAD

**Issue by betatim** [rapidsai/deployment#156]
The "copy" button on code blocks copies the whole contents of the block. For example if the block cotains `$ kubectl get pods` then the `$` at the start of the line will copied as well. Annoying when you then paste the command into a terminal.

A simple solution would be not to write the `$` on one line ode blocks. A more ambitious solution would be to only copy the relevant part of the code block (no leading `$` and none of the command's output).

https://docs.rapids.ai/deployment/nightly/platforms/kubernetes.html

<img width="859" alt="Screenshot 2023-02-22 at 18 43 09" src="https://user-images.githubusercontent.com/1448859/220711606-9faf2ef4-dc47-453f-a35d-c856f100d1d2.png">

**Comment by jacobtomlinson** [comment]
https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells
