### ISSUE TITLE
Environment creation failed on non-GPU system

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#18]
I tried building these docs locally on my MacBook but got the following error when creating the environment.

```console
$ conda env create -f conda/environments/deployment_docs_cuda11.5.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - rapids=22.02
  - cudatoolkit=11.5
```

This makes sense as the system doesn't have a GPU, but I'm curious whether we will actually need RAPIDS and a GPU capable system to build these docs? If we do then we should add a note to the README.

**Comment by mroeschke** [comment]
The docs on main (4ed2649d95e09f72ccfef2fe7eabe412128f7cdc) built fine using https://github.com/rapidsai/deployment/blob/main/conda/environments/deployment_docs.yml, so maybe that can be suggested instead.

Maybe `deployment_docs_cuda11.5.yml` will become useful if we ever need GPU resources for doc testing
