### ISSUE TITLE
Should related files link to GitHub?

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#183]
In #173 we discuss that if users download the example notebook files from GitHub they will have jinja2 templates in them for including the latest RAPIDS release. These templates get populated when building the docs and converting the notebooks to HTML.

In #182 I've updated the extension so that during the build the notebooks also get copied straight through to the output with the templates populated. That way users can download the notebooks directly from the docs with the correct images and versions in to match the docs page.

<img width="942" alt="image" src="https://user-images.githubusercontent.com/1610850/225892012-44fbab1d-2331-481e-b3c0-5dd8c8e19038.png">

However the other related files still link to GitHub. This is nice because GitHub renders them well and provides a nice place to download them from in bulk. However GitHub includes the raw source of the notebook with the jinja2 templates in, so if a user clicks on another related file and then downloads the notebook from GitHub they will get a different file than if they downloaded the notebook directly from the docs.

I see a few options here:
- We leave it as is and accept that some users may run into this edge case.
  - **Pro** users can explore all files on GitHub
  - **Con** users might download the templated notebooks
  - **Con** the behaviour of the links in the "related files" section is inconsistent
  - **Con** related file links are broken in PRs because the files aren't on GitHub yet
- We copy all related files into the build output and link them directly instead of going to GitHub.
  - **Pro** users wont accidentally download the wrong notebook file
  - **Pro** related files work on build previews
  - **Con** users would have to download one file at a time from the docs
  - **Con** we would have to figure out how to display directories. Right now we just show the directory and link it to the directory on GitHub without showing the files inside
- We link to the `notebook.ipynb` somewhere other than the "Related files" section
  - **Pro** the behaviour of the links in the "related files" section is consistent
  - **Con** users might still download the templated notebooks from GitHub when viewing the related files
  - **Con** more overhead and visual clutter
  - **Con** related file links are broken in PRs because the files aren't on GitHub yet

Do folks have thoughts?

**Comment by betatim** [comment]
I'm not sure the pretty rendering is worth it compared to avoiding confused users by having all the files in the build output.

For the cons of "download each file" and "how to show directories": are there many cases where there are more than 2-3 files? Maybe we can ignore these cons for now?

Another idea: is it possible to generate `all-the-files-for-this-example.zip`, include that in the build output and link that instead of individual files?

**Comment by jacobtomlinson** [comment]
> Another idea: is it possible to generate all-the-files-for-this-example.zip, include that in the build output and link that instead of individual files?

Oooh I really like this! Maybe link the zip in addition to the individual files?

**Comment by betatim** [comment]
> Maybe link the zip in addition to the individual files?

I think that is what most people do?! Maybe a reason not to do it is because you still have to solve the "how to view directory" problem.

**Comment by jacobtomlinson** [comment]
Hmm true.

**Comment by betatim** [comment]
Maybe link the notebook if it is the only file and otherwise only show the zip?
