### ISSUE TITLE
Dataset tagging scheme in example notebooks

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#188]
> not sure how I feel about tagging datasets too

_Originally posted by @mroeschke in https://github.com/rapidsai/deployment/pull/185#discussion_r1142636129_

Currently we are adding tags for the datasets we are using. But perhaps it would be more useful for us to be tagging with the dataset format (csv, parquet, etc) and the storage location (S3, GCS, HTTP, etc). I think users are more likely looking for examples of loading data in the same format they use from the same location they store theirs, but probably care less about specific dataset examples.

**Comment by mroeschke** [comment]
> But perhaps it would be more useful for us to be tagging with the dataset format (csv, parquet, etc) and the storage location (S3, GCS, HTTP, etc)

+1 I think that would be more descriptive since not everyone would be familiar with a "common" ml dataset
