### ISSUE TITLE
IBM Cloud + RAPIDS

### ISSUE THREAD

**Issue by marifse** [rapidsai/deployment#20]
Hello,

I have written the document to deploy Rapidsai on IBM cloud using Virtual Server and Kubernetes services. 

So I want to upload them on [Rapids.ai/cloud](http://rapids.ai/cloud) page just like there are the sections for other cloud service providers, AWS, Azure and Google Cloud.

The documents that I have written are uploaded on medium and also tested. The links for them are given below.

[Rapids Deployment on IBM Virtual Server for VPC](https://medium.com/@ahmed_82744/deploy-rapids-on-ibm-cloud-virtual-server-for-vpc-ce3e4b3ede1c)

[Rapids Deployment on IBM Cloud Kubernetes Services](https://medium.com/@ahmed_82744/deploy-rapids-on-ibm-cloud-kubernetes-service-920de68dc6c4)

Thank you.

**Comment by jacobtomlinson** [comment]
This is great thanks so much for opening this issue. We are in the process of migrating documentation from rapids.ai/cloud over to this repo which will end up at docs.rapids.ai once we get things finished up. We are targeting the new deployment docs site for RAPIDS 22.10. 

I'll add this issue to the project board so we can ensure we get these IBM instructions included too.

**Comment by marifse** [comment]
thank you for your positive response. If you have any query, please feel free to ask anytime.

**Comment by marifse** [comment]
@jacobtomlinson may I have the idea by what time it would be available on docs.rapids.ai page (with IBM Cloud Instructions).

**Comment by jacobtomlinson** [comment]
We are planning to launch the new deployment docs in October as part of the `22.10` RAPIDS release

**Comment by marifse** [comment]
@jacobtomlinson thank you for your response. But for now we have tested rapids on IBM cloud using the Helm Chart and Docker image available, I am not sure whether the next Rapids 22.10 version would be compatible with IBM Kubernetes version and updated helm chart would be available for that. Similarly for the docker image. So I would be really grateful if you could update the existing rapids.ai/cloud page with IBM instructions for now.

**Comment by marifse** [comment]
@jacobtomlinson also current Helm chart for RAPIDAI is not supporting the latest Kubernetes version and stuck on error, i had to select the downgraded version 1.21.14 when provisioning IBM Kubernetes cluster. So also check into the helm charts when going to upgrade the documentation for latest version of RAPIDSAI. thank you.

**Comment by jacobtomlinson** [comment]
@marifse we are in a bit of a state of flux here at the moment. The rapids.ai/cloud page is out of date and we do not plan to make any further changes to it. Instead, we are focusing on the new deployment documentation in this repo. When this documentation is published with `22.10` we will redirect the rapids.ai/cloud page to it.

The RAPIDS helm charts have not been maintained for a long time as we saw very little use of them, so I'm not surprised they are not working as expected. We actually [deprecated them](https://helm.rapids.ai/) recently and are going to be providing updated instructions on using RAPIDS with the upstream Dask Helm Chart which is much more active (xref #7).

We are now tracking adding IBM Cloud instructions to the documentation as part of `22.10`, but please accept my apologies that we can't get this out any sooner.

I note that if you search "RAPIDS on IBM Cloud" the top result is this page https://www.ibm.com/cloud/blog/deploy-rapids-on-gpu-enabled-virtual-servers-on-ibm-cloud-virtual-private-cloud which seems to have reasonably up to date instructions, although it would be great to update that to use the latest Docker images which you can find here https://rapids.ai/start.html#get-rapids.

**Comment by marifse** [comment]
@jacobtomlinson thank you for your kind response. We have already published the article for [Rapids on IBM VSI ](https://medium.com/@ahmed_82744/deploy-rapids-on-ibm-cloud-virtual-server-for-vpc-ce3e4b3ede1c) and [Kubernetes](https://medium.com/@ahmed_82744/deploy-rapids-on-ibm-cloud-kubernetes-service-920de68dc6c4) on medium, so this article already using the docker image, so once you will be ready with latest Dask Helm Chart and Docker images, we can update them on medium too and you can include the instructions for IBM from there also. I will be waiting when you done with IBM tracking and include them in your new RAPIDS docks page. Thank you.

**Comment by jacobtomlinson** [comment]
Ok great. FYI your blog post is using `rapidsai/rapidsai:cuda11.2-runtime-ubuntu18.04-py3.7` which is the old style of images. Please use the most up to dater images which you can find on the https://rapids.ai/start.html#get-rapids page. For example the latest release is `rapidsai/rapidsai-core:22.06-cuda11.5-runtime-ubuntu20.04-py3.9`.

**Comment by marifse** [comment]
@jacobtomlinson can you please check now, i have updated [Rapids on IBM VSI](https://medium.com/@ahmed_82744/deploy-rapids-on-ibm-cloud-virtual-server-for-vpc-ce3e4b3ede1c) with latest Rapids Image 22.06.

And [Rapids on Kubernetes](https://medium.com/@ahmed_82744/deploy-rapids-on-ibm-cloud-virtual-server-for-vpc-ce3e4b3ede1c) is the same. Please check and let me know, if there is something else required from my side.

Thank you

**Comment by jacobtomlinson** [comment]
@marifse looks great thanks!

**Comment by marifse** [comment]
@jacobtomlinson hope you be doing great. I just want to confirm whether should i fork this repo and create the pull request after putting IBM EKS and Single instance instrcution in source/cloud/IBM directory or you will manage it by yourself! Please confirm. Thank you

**Comment by jacobtomlinson** [comment]
@marifse that is up to you. A PR would be much appreciated, but if you do not have the time we will get it done ourselves.

As I said we are targeting the `22.10` release for this which will happen in mid-october.

**Comment by marifse** [comment]
@jacobtomlinson i have created the pull request, please check and let me know if any correction required, or do it self if your team can.

Thank you.

**Comment by marifse** [comment]
@jacobtomlinson also the pull request has been failed, no idea why it happened. Can you please look into this. https://github.com/rapidsai/deployment/pull/37

**Comment by marifse** [comment]
@jacobtomlinson I have a query, can I get the website metrics for Rapids.ai, please let me know as IBM cloud requires that. Also any update for IBM cloud page on rapids.ai. Thank you.

**Comment by jacobtomlinson** [comment]
I'm not sure I can share this information. I'm still waiting on IBM Cloud access so that I can review your PR. I'll speak with our IBM Cloud account manager and see how we can proceed with your request.

**Comment by marifse** [comment]
thank you for your response. please check and let me know, and if you need any help regarding IBM Cloud account then please let me know for that too. thanks
