### ISSUE TITLE
L4 Testing

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#209]
Looks like L4 GPUs are [now available on Google Cloud](https://cloud.google.com/blog/products/compute/introducing-g2-vms-with-nvidia-l4-gpus).

It would be great to take these for a spin and make any relevant docs changes.

Some context:
- L4 GPUs replace the older T4 GPUs are are probably going to be most useful for interactive sessions where you want a cheaper GPU and for model serving and inference
- They are in early access some changes may need to be made to your GCP account before you can use them. If so check in with Ops about that.

Tasks:
- [ ] Spin up a VM with L4 instances and try out the RAPIDS container
  - [ ] Run some example notebooks 
  - [ ] Feedback in the deployment channel with any findings
- [ ] **Optionally** Spin up a GKE cluster with L4 nodes and schedule some work on them (if possible currently)

Deliverables:
- [ ] Demo to the rest of the group (or maybe a RAPIDS demo Wednesday)
- [ ] Tweet about it from the RAPIDS account
- [ ] **Optionally** Update deployment docs with references to L4s where it makes sense

**Comment by mroeschke** [comment]
Just noting in our GCP VM docs, the `NVIDIA GPU-Optimized VMI` does not allow for selecting L4 GPUs yet

I created a g2-standard-4 machine with an L4 GPU with their deep learning debian image which has CUDA, then when I tried following https://docs.rapids.ai/deployment/stable/cloud/gcp/compute-engine.html#install-rapids I get

```
(base) mroeschke@l4-test-rapids:~$ docker run --gpus all --rm -it \
>     --shm-size=1g --ulimit memlock=-1 \
>     -p 8888:8888 -p 8787:8787 -p 8786:8786 \
>     rapidsai/rapidsai-core:23.02-cuda11.5-runtime-ubuntu20.04-py3.10
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: nvml error: driver not loaded: unknown.
```

**Comment by jacobtomlinson** [comment]
What does `nvidia-smi` show on that machine? You might need to use `rapidsai/rapidsai-core:23.02-cuda11.8-runtime-ubuntu22.04-py3.10`.

**Comment by mroeschke** [comment]
The GCP Debian Deep Learning VM apparently installs CUDA 11.3 but the `nvidia-smi` in unavailable.

GCP recommends installing CUDA 12 for L4s even though RAPIDS packages are still working on CUDA 12 compatability IIRC: https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#no-secure-boot

When I manually installed the GPU driver with CUDA 12 on the VM:

```
(base) mroeschke@l4-test-rapids-deployment:~$ nvidia-smi
Wed Apr 26 00:01:25 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA L4                       Off| 00000000:00:03.0 Off |                    0 |
| N/A   55C    P0               30W /  75W|      0MiB / 23034MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by jacobtomlinson** [comment]
Sweet! That's exciting to see.

Given that it took a few steps to get to this point I think it would make sense to write a [quick guide for the deployment docs](https://docs.rapids.ai/deployment/stable/guides/).
