### ISSUE TITLE
Tag links are not working

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#232]
Clicking a tag in an example gives a 404.

https://docs.rapids.ai/deployment/stable/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook/

**Comment by mroeschke** [comment]
So think the fix would simply be

```diff
diff --git a/source/_templates/notebooks-tags.html b/source/_templates/notebooks-tags.html
index 29507a2..928c6e3 100644
--- a/source/_templates/notebooks-tags.html
+++ b/source/_templates/notebooks-tags.html
@@ -3,7 +3,7 @@
 <nav id="bd-toc-nav" class="page-toc">
   <div class="tagwrapper">
     {% for tag in notebook_tags %}
-    <a href="../?filters={{ tag }}">
+    <a href="../../?filters={{ tag }}">
       <span class="sd-sphinx-override sd-badge">{{ tag }}</span>
     </a>
     {% endfor %}
```

But I think that would break checking this locally since these notebooks end with `notebook.html` as opposed to `notebook`. (I am not really sure why this is). Are we okay with that?

**Comment by mroeschke** [comment]
Yeah the notebook url route is:

Deployed: `.../examples/rapids-autoscaling-multi-tenant-kubernetes/notebook/`
Local: `.../examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.html`

so the original `href="../?filters={{ tag }}"` will have a different meaning between these routes

**Comment by jacobtomlinson** [comment]
It would be good to make those consistent. Would you mind looking into what is causing the difference?

**Comment by mroeschke** [comment]
In terms of consistency, not sure if this is a Sphinx related issue.

Visiting https://docs.rapids.ai/deployment/stable/examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.html will redirect to `/notebook/`, so I'm guessing the server is doing this specifically(?). This is starting to be out of my wheelhouse but I don't think this is something we can easily configure from the sphinx build side to be consistent

**Comment by jacobtomlinson** [comment]
It's a static site so I would be surprised if it was unrelated to Sphinx. Perhaps @ajschmidt8 has any thoughts here. Could the way we are hosting this be causing the URL to be rewritten?

**Comment by ajschmidt8** [comment]
> Yeah the notebook url route is:
> 
> Deployed: `.../examples/rapids-autoscaling-multi-tenant-kubernetes/notebook/` Local: `.../examples/rapids-autoscaling-multi-tenant-kubernetes/notebook.html`
> 
> so the original `href="../?filters={{ tag }}"` will have a different meaning between these routes

The difference is likely caused by the Sphinx builder that's being used for local docs vs. deployed docs.

In the PR below, I switched the Sphinx builder to use `dirhtml` instead of `html` so that "pretty URLs" (e.g. URLs without file extensions) are generated.

- https://github.com/rapidsai/deployment/pull/219

This probably needs to also be updated in whatever scripts are being used to generate the docs locally.

**Comment by ajschmidt8** [comment]
If you're running `make html` locally, then you just need to switch to `make dirhtml` instead.
