### ISSUE TITLE
Document how to generate password blobs for Jupyter

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#26]
In #7 there is a mention of how to change the Jupyter password, but the instruction is "compute the hash". We should add a couple of instructions to tell the user how exactly to generate this hash.

https://github.com/rapidsai/deployment/blob/b7e667a4dd9ab42fe86293942cb99e17d2018853/source/tools/kubernetes/dask-helm-chart.md?plain=1#L32

**Comment by isVoid** [comment]
Where should we put this instruction?

**Comment by jacobtomlinson** [comment]
That's a nice neat way of doing it! I would put it immediately after the line I linked above.
