### ISSUE TITLE
Update conf.py for new Docker setup

### ISSUE THREAD

**Issue by jarmak-nv** [rapidsai/deployment#270]
Docs reference the old notebook structure. Haven't tested anything yet, but 

`$ docker build --tag <username>/rapids_databricks:latest --build-arg RAPIDS_IMAGE=rapidsai/rapidsai-core-nightly:23.08-cuda11.8-runtime-ubuntu22.04-py3.10 ./docker`

needs to use the new docker location similar to below.

`$ docker build --tag <username>/rapids_databricks:latest --build-arg RAPIDS_IMAGE=rapidsai/base:23.08a-cuda11.8-py3.10 ./docker`

**Comment by jarmak-nv** [comment]
Edit: looks like this is defined by the variable `rapids_container` - time to find out where that lives to update it (or if it's inherited from the main docs page, will need to PR there.)

**Comment by jacobtomlinson** [comment]
Closed by #271
