### ISSUE TITLE
Write Container Canary tests for DLFW

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#277]

**Comment by jameslamb** [comment]
Adding some links.

Container canary: https://github.com/NVIDIA/container-canary

NVIDIA Base Command Platform ("BCP"): https://docs.nvidia.com/base-command-platform/index.html

Example using the RAPIDS containers: https://docs.nvidia.com/base-command-platform/user-guide/latest/index.html#dask-and-rapids-quick-start-jobs-multi-node

> **11.1.2. Dask and RAPIDS Quick Start Jobs (Multi-node)[](https://docs.nvidia.com/base-command-platform/user-guide/latest/index.html#dask-and-rapids-quick-start-jobs-multi-node)**
> 
> _All clusters have a Dask & RAPIDS Quick Start launch enabled by default... The RAPIDS libraries provide a range of open-source GPU-accelerated Data Science libraries._ 
> 
> _..._
> 
> _Click Launch JupyterLab in the top right corner of the page. A JupyterLab environment running inside the Dask & RAPIDS container will be launched in a new tab._

**Comment by jameslamb** [comment]
Opened an issue over in `rapidsai/docker`: https://github.com/rapidsai/docker/issues/667

**Comment by jameslamb** [comment]
Linking this related issue: https://github.com/rapidsai/docker/issues/582

**Comment by jameslamb** [comment]
Since this was re-scoped to "for DLFW"... this can be closed! That now-complete work happened in a private repo (I shared the link internally).

We have this separate issue tracking adding similar tests for the `rapidsai/docker` images: https://github.com/rapidsai/docker/issues/667. I've added that to the Deployment board.
