### ISSUE TITLE
[DOCS] update {{rapids_container}} version in stable docs

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/deployment#282]
In the docs pages of https://docs.rapids.ai/deployment/stable/platforms/kubeflow/ and https://docs.rapids.ai/deployment/stable/platforms/kubernetes/, I found that the version of RAPIDS container is now legacy (23.06) instead of stable (23.08).  It seems that this is autogenerated from the docs with the `{{rapids_container}}` tag in the md files
 https://github.com/rapidsai/deployment/blob/main/source/platforms/kubeflow.md and https://github.com/rapidsai/deployment/blob/main/source/platforms/kubernetes.md respectively.  Other pages may be affected.  Nightly is not affected

**Comment by jacobtomlinson** [comment]
It looks like the repo did not get tagged as part of the 23.08 release yet. cc @raydouglass

**Comment by jacobtomlinson** [comment]
Tags have been created since
