### ISSUE TITLE
Explore how to write custom checks for `conda doctor`.

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#421]

**Comment by melodywang060** [comment]
-implement conda subcommands (this [tutorial](https://github.com/conda/conda-plugin-template/blob/main/tutorials/subcommands/python/README.md) was really helpful)
-granulize different checks in different functions using conda[ health_checks](https://docs.conda.io/projects/conda/en/latest/dev-guide/plugins/health_checks.html) 
- follow the [development environment](https://docs.conda.io/projects/conda/en/latest/dev-guide/development-environment.html) setup if you want to test in the local conda repository

**Comment by melodywang060** [comment]
RAPIDS-specific health checks : 
based off of the [setup requirements](https://docs.rapids.ai/install)

Required: 
- GPU compute capability `check_gpu_compute_capability()`
- OS version compatibility `check_os_compatibility()` 
- Driver & CUDA compatibility : `detect_driver_compatibility()`

Recommended: 
- NVMe SSD Detection: `check_sdd_nvme()`
- system Memory to GPU Memory  2:1 ratio: `check_memory_to_gpu_ratio()`
- NVLink with 2 or more GPUs: `check_nvlink_status()`
