### ISSUE TITLE
Use inline tab plugins for "alternative workflows"

### ISSUE THREAD

**Issue by isVoid** [rapidsai/deployment#44]
Frequently in user guide documents we want to show multiple ways to achieve the same end goal. For example in [Azure CSP setup doc](https://github.com/rapidsai/deployment/blob/main/source/cloud/azure/single-node.md#azure-single-node-rapids), user can setup cloud resources via CLI or through Azure portal. User only need to pick one or the other so showing both information on the screen is taxing for user.

Similar to [cython tutorial](https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html#primes), we can use plugins [`sphinx-tab`](https://sphinx-tabs.readthedocs.io/en/latest/) to only show portion of the guides. Currently it doesn't work well with RAPIDS doc-site's dark theme.

**Comment by jacobtomlinson** [comment]
Closed in #43
