### ISSUE TITLE
Images not rendering in rapids-sagemaker-hpo notebook

### ISSUE THREAD

**Issue by ncclementi** [rapidsai/deployment#468]
In https://docs.rapids.ai/deployment/stable/examples/rapids-sagemaker-hpo/notebook/ I don't see the images rendering (tried 3 different browser and I have the same problem)

For example:

![Image](https://github.com/user-attachments/assets/c5459df2-0bbd-48a2-acf1-a7ddb390f293)

I can't reproduce locally, in the local build they do render properly. 

I think the problem is because images are inserted using this format 

```python
<img src='../../_static/images/examples/rapids-sagemaker-hpo/hpo.png'>
``` 

instead of this

```python
![](../../_static/images/examples/rapids-sagemaker-hpo/hpo.png)
```

but I'm not entirely sure, if someone can confirm they see the same and it's not just on my end, I'm happy to open a PR.

**Comment by jameslamb** [comment]
Thanks for reporting this @ncclementi ! I see that same rendering issue on that page.

For my own understanding, how would switching from HTML `<img>` tags to markdown-style hyperlinks, but using the exact same relative path, fix this?

Anyway yeah, we'd be grateful for a PR to fix this if you have the time and interest. CI here renders a full preview of the site, so we'd be able to test directly with that.

**Comment by jacobtomlinson** [comment]
I think Sphinx replaces relative markdown links with the correct urls. For example the `_static` directory ends up getting mapped to something else and Sphinx handles the translation during the markdown parsing.
