### ISSUE TITLE
RAPIDS Deployment docs 24.10.00 release build failed

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#471]
It looks like the [`24.10.00` tag build workflow failed](https://github.com/rapidsai/deployment/actions/runs/11280556033). This was caused by #463. 

It seems that Sphinx cut a new release `8.1.0` between the last PR that was merged here on Wednesday and the release being tagged yesterday which broke the build.

![Image](https://github.com/user-attachments/assets/772087bb-1794-403e-ace6-1d044b215b47)

I've opened #470 which adds an upper bound to Sphinx and gets the build working again. We need to merge that and then make a HOTFIX release here. @raydouglass could you handle this?

Long term I've also opened https://github.com/mgaitan/sphinxcontrib-mermaid/pull/161 which fixes the problem upstream and means we can remove our upper bound pin again once that fix is released in `sphinxcontrib-mermaid`.

**Comment by jacobtomlinson** [comment]
#470 is now merged and builds are passing on main again. So just need another tag now.

**Comment by raydouglass** [comment]
Pushed a new tag and now monitoring the build: https://github.com/rapidsai/deployment/actions/runs/11292946252

**Comment by raydouglass** [comment]
Looks like it was successful!
