### ISSUE TITLE
Nightly releases keep failing

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/deployment#66]
The build and push action keeps failing when building the nightly docs on main. It seems to collide with other repos also pushing to the RAPIDS docs repo.

I've seen 3 instances of the push failing because a new commit has been pushed between the action pulling, committing and pushing. I've also seen one instance of it successfully pushing but another repo force pushing over the top.

Ideally other repos don't force push and all repos should try pulling, rebasing and pushing again if it fails the first time.

**Comment by jacobtomlinson** [comment]
There is a plan to change the way the docs are published later in the year. It's likely this will not be fixed until then. Moving to backlog.

**Comment by jameslamb** [comment]
I think this can be closed. We're successfully building nightly docs here. Here's an example:

* builds: https://github.com/rapidsai/deployment/actions/workflows/build-and-deploy.yml
* docs: https://docs.rapids.ai/deployment/nightly/
