### ISSUE TITLE
GCP deployment instructions - update Vertex AI and AI Cloud Platform

### ISSUE THREAD

**Issue by sophwats** [rapidsai/deployment#71]
The [RAPIDS ai Google Cloud install instructions](https://rapids.ai/cloud#GC-AI) point users to deploy "RAPIDS 0.18[EXPERIMENTAL]" notebook instances within AI Cloud platform.  This notebook instance type no longer exists. 

Since GCP is now pushing Vertex AI over AI Platform, it may make sense to also update the instructions to assume devs are using Vertex AI.

**Comment by mroeschke** [comment]
Just noting that our next stable release of the newer deployment docs eliminates AI platform entirely but still had a reference to `RAPIDS 0.18[EXPERIMENTAL]` in the Vertex AI section https://docs.rapids.ai/deployment/nightly/cloud/gcp/index.html

**Comment by sophwats** [comment]
Awesome - thanks Matthew
